// Package timelineapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package timelineapi

import (
	"time"
)

// Actor defines model for Actor.
type Actor struct {
	Id    int    `json:"id"`
	Login string `json:"login"`
}

// CommentContext defines model for CommentContext.
type CommentContext struct {
	Body             *string `json:"body,omitempty"`
	DiffHunk         *string `json:"diff_hunk,omitempty"`
	Line             *int    `json:"line,omitempty"`
	OriginalPosition *int    `json:"original_position,omitempty"`
	Path             *string `json:"path,omitempty"`
	Position         *int    `json:"position,omitempty"`
	ReviewId         *int    `json:"review_id,omitempty"`
	StartLine        *int    `json:"start_line,omitempty"`
	ThreadId         *string `json:"thread_id,omitempty"`
	Url              *string `json:"url,omitempty"`
}

// CommitContext defines model for CommitContext.
type CommitContext struct {
	Sha *string `json:"sha,omitempty"`
	Url *string `json:"url,omitempty"`
}

// Event defines model for Event.
type Event struct {
	Actor      *Actor           `json:"actor,omitempty"`
	Comment    *CommentContext  `json:"comment,omitempty"`
	Commit     *CommitContext   `json:"commit,omitempty"`
	DiffUrl    *string          `json:"diff_url,omitempty"`
	Event      *string          `json:"event,omitempty"`
	Id         string           `json:"id"`
	Issue      *IssueOpenedData `json:"issue,omitempty"`
	OccurredAt time.Time        `json:"occurred_at"`
	Pr         *PROpenedData    `json:"pr,omitempty"`
	Type       string           `json:"type"`
}

// IssueOpenedData defines model for IssueOpenedData.
type IssueOpenedData struct {
	Body  string `json:"body"`
	Title string `json:"title"`
}

// PROpenedData defines model for PROpenedData.
type PROpenedData struct {
	Body  string `json:"body"`
	Title string `json:"title"`
}

// RepositoryRef defines model for RepositoryRef.
type RepositoryRef struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}

// TimelineResponse defines model for TimelineResponse.
type TimelineResponse struct {
	Events     []Event       `json:"events"`
	PullNumber int           `json:"pull_number"`
	Repository RepositoryRef `json:"repository"`
}
