// Package notificationsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package notificationsapi

import (
	"time"
)

// Defines values for NotificationTargetKind.
const (
	Issue NotificationTargetKind = "issue"
	Pr    NotificationTargetKind = "pr"
)

// NotificationEvent defines model for NotificationEvent.
type NotificationEvent struct {
	Id         string              `json:"id"`
	Repository RepositoryRef       `json:"repository"`
	Subject    NotificationSubject `json:"subject"`
	Target     NotificationTarget  `json:"target"`
	UpdatedAt  time.Time           `json:"updated_at"`
}

// NotificationSubject defines model for NotificationSubject.
type NotificationSubject struct {
	Title string `json:"title"`
	Type  string `json:"type"`
	Url   string `json:"url"`
}

// NotificationTarget defines model for NotificationTarget.
type NotificationTarget struct {
	Kind   NotificationTargetKind `json:"kind"`
	Number int                    `json:"number"`
	Ref    string                 `json:"ref"`
}

// NotificationTargetKind defines model for NotificationTarget.Kind.
type NotificationTargetKind string

// RepositoryRef defines model for RepositoryRef.
type RepositoryRef struct {
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
}
